name: examples 0.12

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
  push:
    branches: [main, test-mac]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          brew install wget git curl
      - name: Install Rust target
        run: |
          rustup target add wasm32-wasi
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile default
      - name: Install WasmEdge
        run: |
          VERSION=0.11.2
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -e all --version=$VERSION --tf-version=$VERSION --tf-deps-version=$VERSION --tf-tools-version=$VERSION --image-version=$VERSION  -p /usr/local

      # Disable this example due to it relies on wasmedge_http_req, which is a cyclic dependence
      # - name: HTTP client example
      #   run: |
      #     cd examples/http_client/
      #     cargo build --target wasm32-wasi --release
      #     wasmedge target/wasm32-wasi/release/http_client.wasm

      - name: HTTP async client example
        run: |
          cd examples/nonblock_http_client/
          cargo build --target wasm32-wasi --release
          wasmedge target/wasm32-wasi/release/nonblock_http_client.wasm

      - name: HTTP server example
        run: |
          cd examples/http_server/
          cargo build --target wasm32-wasi --release
          nohup wasmedge target/wasm32-wasi/release/http_server.wasm &
          echo $! > wasmedge.pid
          wasmedge_pid=$(cat wasmedge.pid)
          sleep 5
          resp=$(curl -X POST http://127.0.0.1:1234 -d "name=WasmEdge")
          echo "Server response is $resp"
          resp=$(curl -X POST http://127.0.0.1:1234 -d "name=WasmEdge")
          resp=$(curl -X POST http://127.0.0.1:1234 -d "name=WasmEdge")
          resp=$(curl -X POST http://127.0.0.1:1234 -d "name=WasmEdge")
          resp=$(curl -X POST http://127.0.0.1:1234 -d "name=WasmEdge")
          resp=$(curl -X POST http://127.0.0.1:1234 -d "name=WasmEdge")
          kill -9 $wasmedge_pid
          rm wasmedge.pid

      - name: UDP Socket Example
        run: |
          cargo build --target wasm32-wasi --example=udp_socket --release
          wasmedge target/wasm32-wasi/release/examples/udp_socket.wasm

      - name: DNS Example
        run: |
          cargo build --target wasm32-wasi --example=get_addrinfo --release
          wasmedge target/wasm32-wasi/release/examples/get_addrinfo.wasm

      - name: ToSocketAddrs Example
        run: |
          cargo build --target wasm32-wasi --example=socket_addr --release
          wasmedge target/wasm32-wasi/release/examples/socket_addr.wasm
